### ISSUE TITLE
OpenAM 5.5 and Liferay DXP 7

### ISSUE THREAD

**Issue by bodyfake** [finalist/liferay-oidc-plugin#14]
Hello, 

i used following setup: 

openidconnect.enableOpenIDConnect=true
openidconnect.token-location=http://local.test-server.ag:7070/openam/oauth2/access_token
openidconnect.authorization-location=http://local.test-server.ag:7070/openam/oauth2/authorize
openidconnect.profile-uri=http://local.test-server.ag:7070/openam/oauth2/userinfo
openidconnect.issuer=http://local.test-server.ag:7070/openam/oauth2
openidconnect.client-id=MyId
openidconnect.secret=xxxxxxx
openidconnect.scope=openid email

If I go to http://local.test-server.ag:8080/kundenportal/c/portal/login I get redirect to OpenAM and I can login successfull.
Than I got redirected to Liferay with following Link:

http://local.test-server.ag:8080/kundenportal/c/portal/login?code=e2ab2018-a609-4b8b-b38f-92f96510cd40&scope=openid%20email&iss=http%3A%2F%2Flocal.test-server.ag%3A7070%2Fopenam%2Foauth2&state=70b6ce8b4a2acf6505103e3ccd9ed06a&client_id=MyId

I increased the DEBUG Lebel for nl.finalist in Liferay to ALL

I got following in the Liferay Logs.
Caused by: OAuthProblemException{error='invalid_client', description='Invalid authentication method for accessing this endpoint.', uri='null', state='null', scope='null', redirectUri='null', responseStatus=400, parameters={}}
	at org.apache.oltu.oauth2.common.exception.OAuthProblemException.error(OAuthProblemException.java:59)
	at org.apache.oltu.oauth2.client.validator.OAuthClientValidator.validateErrorResponse(OAuthClientValidator.java:63)
	at org.apache.oltu.oauth2.client.validator.OAuthClientValidator.validate(OAuthClientValidator.java:48)
	at org.apache.oltu.oauth2.client.response.OAuthClientResponse.validate(OAuthClientResponse.java:127)
	at org.apache.oltu.oauth2.client.response.OAuthClientResponse.init(OAuthClientResponse.java:96)
	at org.apache.oltu.oauth2.client.response.OAuthAccessTokenResponse.init(OAuthAccessTokenResponse.java:65)
	at org.apache.oltu.oauth2.client.response.OAuthClientResponse.init(OAuthClientResponse.java:101)
	at org.apache.oltu.oauth2.client.response.OAuthAccessTokenResponse.init(OAuthAccessTokenResponse.java:60)
	at nl.finalist.liferay.oidc.OpenIdConnectResponse.init(OpenIdConnectResponse.java:35)
	at org.apache.oltu.oauth2.client.response.OAuthClientResponse.init(OAuthClientResponse.java:120)
	at org.apache.oltu.oauth2.client.response.OAuthClientResponseFactory.createCustomResponse(OAuthClientResponseFactory.java:82)
	at org.apache.oltu.oauth2.client.URLConnectionClient.execute(URLConnectionClient.java:111)
	at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:65)
	at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:55)
	at nl.finalist.liferay.oidc.LibFilter.exchangeCodeForAccessToken(LibFilter.java:168)
	... 87 more

Do I miss something? Or why are all necessary fields null? 

Greetings Julian

**Comment by bodyfake** [comment]
I found the mistake:
For OpenAM you need to use client_secret_post.
