### ISSUE TITLE
What properties I need to update if we use our own Open ID Connect

### ISSUE THREAD

**Issue by karthikreddym** [finalist/liferay-oidc-plugin#24]
Dear Team,

we have configured with below values in portal-ext.properties but where I need to update the redirection URL and also I am not understanding the plugin as when we can see the changes and where we can see the plugin changes

openidconnect.enableOpenIDConnect=true
openidconnect.token-location=Custom Value Provided
openidconnect.authorization-location=Custom Value Provided
openidconnect.client-id= Custom Value Provided
openidconnect.secret= Custom Value Provided
openidconnect.scope= Custom Value Provided
openidconnect.profile-uri=Custom Value Provided
openidconnect.issuer=Custom Value Provided

Here we have a value as issuer but as per the plugin do we have any standard value for this. Please help me with the above values and also with google plugin.

Thanks & Regards,
   Karthik

**Comment by gvanderploeg** [comment]
> as when we can see the changes and where we can see the plugin changes

Wat do you mean? If you change the properties in portal-ext.properties you need to restart the portal.

> but where I need to update the redirection URL

The redirect URI will be generated by Liferay automatically during the OpenID Connect flow. On the OP side (identity provider) you should whitelist one or more URIs, depending on how many sites/environments you want to support. These URIs are in the form: `http(s)://[your-public-liferay-site]/c/portal/login`
So especially the `/c/portal/login` part is crucial and static, the rest depends on your specific setup.

> Here we have a value as issuer but as per the plugin do we have any standard value for this. 

Your Identity Provider should provide this value. According to your OP's discovery document (https://fssfed.stage.ge.com/fss/.well-known/openid-configuration) the value you use is correct.

> Please help me with the above values and also with google plugin.

What do you mean with google plugin?

**Comment by karthikreddym** [comment]
Hi gvanderploeg,

   Thanks for your quick reply .
you need to restart the portal --> This step already I did and faced the error as
```
java.lang.IllegalStateException: Page needs a session and none is available
	at org.apache.jasper.runtime.PageContextImpl._initialize(PageContextImpl.java:148)
	at org.apache.jasper.runtime.PageContextImpl.initialize(PageContextImpl.java:125)
	at org.apache.jasper.runtime.JspFactoryImpl.internalGetPageContext(JspFactoryImpl.java:112)
	at org.apache.jasper.runtime.JspFactoryImpl.getPageContext(JspFactoryImpl.java:65)
	at com.liferay.portal.kernel.servlet.JspFactoryWrapper.getPageContext(JspFactoryWrapper.java:63)
	at org.apache.jsp.html.common.themes.portlet_jsp._jspService(portlet_jsp.java:419)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:96)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:749)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:605)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:544)
	at com.liferay.portlet.PortletRequestDispatcherImpl.dispatch(PortletRequestDispatcherImpl.java:331)
	at com.liferay.portlet.PortletRequestDispatcherImpl.include(PortletRequestDispatcherImpl.java:128)
	at com.liferay.portal.struts.PortletRequestProcessor.doInclude(PortletRequestProcessor.java:370)
	at com.liferay.portal.struts.PortletRequestProcessor.doForward(PortletRequestProcessor.java:338)
	at org.apache.struts.tiles.TilesRequestProcessor.processTilesDefinition(TilesRequestProcessor.java:239)
	at org.apache.struts.tiles.TilesRequestProcessor.processForwardConfig(TilesRequestProcessor.java:302)
	at com.liferay.portal.struts.PortletRequestProcessor.processForwardConfig(PortletRequestProcessor.java:478)
	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:241)
	at com.liferay.portal.struts.PortletRequestProcessor.process(PortletRequestProcessor.java:234)
	at com.liferay.portlet.StrutsPortlet.include(StrutsPortlet.java:296)
	at com.liferay.portlet.StrutsPortlet.doView(StrutsPortlet.java:157)
	at com.liferay.portal.kernel.portlet.LiferayPortlet.doDispatch(LiferayPortlet.java:213)
	at javax.portlet.GenericPortlet.render(GenericPortlet.java:233)
	at com.liferay.portlet.FilterChainImpl.doFilter(FilterChainImpl.java:103)
	at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:55)
	at com.liferay.portlet.FilterChainImpl.doFilter(FilterChainImpl.java:100)
	at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:64)
	at com.liferay.portlet.InvokerPortletImpl.invoke(InvokerPortletImpl.java:618)
	at com.liferay.portlet.InvokerPortletImpl.invokeRender(InvokerPortletImpl.java:677)
	at com.liferay.portlet.InvokerPortletImpl.render(InvokerPortletImpl.java:379)
	at org.apache.jsp.html.portal.render_005fportlet_jsp._jspService(render_005fportlet_jsp.java:1230)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at com.liferay.portal.servlet.DirectRequestDispatcher.include(DirectRequestDispatcher.java:57)
	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.doDispatch(ClassLoaderRequestDispatcherWrapper.java:78)
	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.include(ClassLoaderRequestDispatcherWrapper.java:53)
	at com.liferay.portlet.PortletContainerImpl._doRender(PortletContainerImpl.java:655)
	at com.liferay.portlet.PortletContainerImpl.render(PortletContainerImpl.java:138)
	at com.liferay.portlet.SecurityPortletContainerWrapper.render(SecurityPortletContainerWrapper.java:141)
	at com.liferay.portlet.RestrictPortletContainerWrapper.render(RestrictPortletContainerWrapper.java:126)
	at com.liferay.portal.kernel.portlet.PortletContainerUtil.render(PortletContainerUtil.java:156)
	at com.liferay.portal.layoutconfiguration.util.PortletRenderer._render(PortletRenderer.java:120)
	at com.liferay.portal.layoutconfiguration.util.PortletRenderer.access$4(PortletRenderer.java:107)
	at com.liferay.portal.layoutconfiguration.util.PortletRenderer$PortletRendererCallable.doCall(PortletRenderer.java:174)
	at com.liferay.portal.layoutconfiguration.util.PortletRenderer$PortletRendererCallable.doCall(PortletRenderer.java:1)
	at com.liferay.portal.kernel.executor.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:69)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask._runTask(ThreadPoolExecutor.java:682)
	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask.run(ThreadPoolExecutor.java:593)
	at java.lang.Thread.run(Unknown Source)
```

 I will try to implement the remaining points as mentioned for the URIs .
And about google plugin  Its not a google plugin sorry for that if I want to connect with google then is there any sample working values where i can copy in portal-ext.properties to see the result how it works and what configuration I need to update other than portal-ext.properties after deploying the lpkg file.

**Comment by gvanderploeg** [comment]
The stacktrace you provided is a very generic one, I doubt that it has anything to do with the OIDC plugin...

The README.md contains a [complete example of a Google-compatible configuration](https://github.com/finalist/liferay-oidc-plugin/blob/oidc-parent-0.5.2/README.md#complete-copy-paste-friendly-code-block-with-all-required-properties).

**Comment by karthikreddym** [comment]
Dear gvanderploeg,

  Thank you for your support. Now I am able to redirect using plugin
Here my doubt is after successfully  redirected and authenticated again it's redirected to liferay login page. So please let me know the flow how it happen usually.

Thanks & Regards,
  Karthik

**Comment by gvanderploeg** [comment]
The redirect should point you to the 'default landing page' in Liferay.
If you get a liferay login page again after logging in with OIDC, apparently there is something missing in the id token or the user info response.
To debug this, change the log level of package 'nl.finalist' in Liferay to DEBUG or TRACE. This will shed a light on what information is transferred between OP and Liferay.
