### ISSUE TITLE
Invalid state parameter

### ISSUE THREAD

**Issue by neyanderson** [finalist/liferay-oidc-plugin#25]
Hi

I've seem sometimes it on log:

```
16:45:17,622 INFO  [http-nio-8080-exec-26][Liferay70Adapter:55] Provided state parameter '6a4de044ab2e0d5dd245bcaef8408258' does not equal expected '442ce034d59ff6aff3bf09a2ec6ae8c7', cannot
 continue.
13-Apr-2018 16:45:17.623 SEVERE [http-nio-8080-exec-26] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Main Servlet] in context with path [] threw except
ion
 java.io.IOException: Invalid state parameter
        at nl.finalist.liferay.oidc.LibFilter.exchangeCodeForAccessToken(LibFilter.java:205)
        at nl.finalist.liferay.oidc.LibFilter.processFilter(LibFilter.java:164)
        at nl.finalist.liferay.oidc.OpenIDConnectFilter.processFilter(OpenIDConnectFilter.java:61)
```

Using CE 7 GA4 + Tomcat + Azure and plugin 0.4.0

Any suggestion ?

**Comment by gvanderploeg** [comment]
Apparently a mismatch between sessions on the Liferay side and the IDP side. This could happen when users try to continue a sign-in flow after first interrupting it and letting it time out, I think.
Are you able to reproduce it yourself?

**Comment by rambocloack** [comment]
Je suis absent(e) du bureau jusqu'au 23/04/2018

Bonjour,

Je suis absent du 16/04/2018 au 20/04/2018.
Je répondrais à votre message dès mon retour.
Pour toutes demandes merci de bien vouloir vous adresser au
Support-Technique Isocel par mail à l'adresse suivante:
support-technique.isocel@isocel.info ou par téléphone au 0524549961.

Cordialement Richard AMBAUD


Remarque : ceci est une réponse automatique à votre message  "Re:
[finalist/liferay-oidc-plugin] Invalid state parameter (#25)" envoyé le
16/04/2018 11:13:14.

C'est la seule notification que vous recevrez pendant l'absence de cette
personne.

**Comment by neyanderson** [comment]
I can't reproduce, but some users has report me this message on screen.

![image](https://user-images.githubusercontent.com/16106860/38813180-adecf86e-4164-11e8-97ec-95201d3143cf.png)

What you suggest see or analysis on reproduce ?

**Comment by rambocloack** [comment]
Je suis absent(e) du bureau jusqu'au 23/04/2018

Bonjour,

Je suis absent du 16/04/2018 au 20/04/2018.
Je répondrais à votre message dès mon retour.
Pour toutes demandes merci de bien vouloir vous adresser au
Support-Technique Isocel par mail à l'adresse suivante:
support-technique.isocel@isocel.info ou par téléphone au 0524549961.

Cordialement Richard AMBAUD


Remarque : ceci est une réponse automatique à votre message  "Re:
[finalist/liferay-oidc-plugin] Invalid state parameter (#25)" envoyé le
16/04/2018 16:09:19.

C'est la seule notification que vous recevrez pendant l'absence de cette
personne.

**Comment by thamamo** [comment]
Hello there,

I am also facing the same 'Invalid state parameter' error.
When I checked the request, the redirect URI was http instead of https, and I suspect that's the problem.

But I don't know how to change this parameter.
Would you tell me how to change it?

Best regards,
thamamo
