### ISSUE TITLE
Repo maven releases

### ISSUE THREAD

**Issue by jotaceperez** [finalist/liferay-oidc-plugin#6]
Hi,

I am trying to compile the oidc-plugin component and throws me an error regarding the maven repository. When I test the URL, it tells me Access Denied. You can help me with that. 
Thank you.

**Comment by gvanderploeg** [comment]
Please paste the complete stacktrace, thanks.

**Comment by jotaceperez** [comment]
This is the complete stacktrace.

[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for nl.finalist.liferay.oidc:oidc-parent:0.2.3-SNAPSHOT: Could not transfer artifact nl.iprofs.pom:parent:pom:2.0.24 from/to releases-public (https://nexus.iprofs.nl/content/repositories/releases-public): Access denied to https://nexus.iprofs.nl/content/repositories/releases-public/nl/iprofs/pom/parent/2.0.24/parent-2.0.24.pom. Error code 401, Unauthorized and 'parent.relativePath' points at wrong local POM @ line 5, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for nl.finalist.liferay.oidc:oidc-parent:0.2.3-SNAPSHOT: Could not transfer artifact nl.iprofs.pom:parent:pom:2.0.24 from/to releases-public (https://nexus.iprofs.nl/content/repositories/releases-public): Access denied to https://nexus.iprofs.nl/content/repositories/releases-public/nl/iprofs/pom/parent/2.0.24/parent-2.0.24.pom. Error code 401, Unauthorized and 'parent.relativePath' points at wrong local POM @ line 5, column 13

	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:422)
	at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:419)
	at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:410)
	at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:83)
	at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:491)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]   
[ERROR]   The project nl.finalist.liferay.oidc:oidc-parent:0.2.3-SNAPSHOT (/Users/jcperez/Proyectos/bicevida/liferay-oidc-plugin/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for nl.finalist.liferay.oidc:oidc-parent:0.2.3-SNAPSHOT: Could not transfer artifact nl.iprofs.pom:parent:pom:2.0.24 from/to releases-public (https://nexus.iprofs.nl/content/repositories/releases-public): Access denied to https://nexus.iprofs.nl/content/repositories/releases-public/nl/iprofs/pom/parent/2.0.24/parent-2.0.24.pom. Error code 401, Unauthorized and 'parent.relativePath' points at wrong local POM @ line 5, column 13 -> [Help 2]
org.apache.maven.model.resolution.UnresolvableModelException: Could not transfer artifact nl.iprofs.pom:parent:pom:2.0.24 from/to releases-public (https://nexus.iprofs.nl/content/repositories/releases-public): Access denied to https://nexus.iprofs.nl/content/repositories/releases-public/nl/iprofs/pom/parent/2.0.24/parent-2.0.24.pom. Error code 401, Unauthorized
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:197)
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:246)
	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1000)
	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:800)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:329)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:469)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:438)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:401)
	at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:419)
	at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:410)
	at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:83)
	at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:491)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact nl.iprofs.pom:parent:pom:2.0.24 from/to releases-public (https://nexus.iprofs.nl/content/repositories/releases-public): Access denied to https://nexus.iprofs.nl/content/repositories/releases-public/nl/iprofs/pom/parent/2.0.24/parent-2.0.24.pom. Error code 401, Unauthorized
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:193)
	... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact nl.iprofs.pom:parent:pom:2.0.24 from/to releases-public (https://nexus.iprofs.nl/content/repositories/releases-public): Access denied to https://nexus.iprofs.nl/content/repositories/releases-public/nl/iprofs/pom/parent/2.0.24/parent-2.0.24.pom. Error code 401, Unauthorized
	at io.takari.aether.connector.AetherRepositoryConnector$2.wrap(AetherRepositoryConnector.java:895)
	at io.takari.aether.connector.AetherRepositoryConnector$2.wrap(AetherRepositoryConnector.java:1)
	at io.takari.aether.connector.AetherRepositoryConnector$GetTask.flush(AetherRepositoryConnector.java:673)
	at io.takari.aether.connector.AetherRepositoryConnector.get(AetherRepositoryConnector.java:310)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 29 more
Caused by: io.takari.aether.connector.AuthorizationException: Access denied to https://nexus.iprofs.nl/content/repositories/releases-public/nl/iprofs/pom/parent/2.0.24/parent-2.0.24.pom. Error code 401, Unauthorized
	at io.takari.aether.connector.AetherRepositoryConnector.handleResponseCode(AetherRepositoryConnector.java:369)
	at io.takari.aether.connector.AetherRepositoryConnector.access$8(AetherRepositoryConnector.java:363)
	at io.takari.aether.connector.AetherRepositoryConnector$GetTask.resumableGet(AetherRepositoryConnector.java:603)
	at io.takari.aether.connector.AetherRepositoryConnector$GetTask.run(AetherRepositoryConnector.java:453)
	at io.takari.aether.connector.AetherRepositoryConnector.get(AetherRepositoryConnector.java:304)
	... 31 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by gvanderploeg** [comment]
Thanks for pointing this out.
I raised an internal ticket about this; I my opinion this repo should allow unauthenticated access indeed. Please bear with me...

**Comment by jotaceperez** [comment]
Of course I will have patience, the plugin is great and I am working to get roles from the tokenid and be able to assign them to liferay dynamically. Of course if this contribution serves, I will add it for public use

**Comment by jotaceperez** [comment]
I try again and work fine. Thanks for all your support.

Please close this thread.

**Comment by gvanderploeg** [comment]
Thanks for reporting back, I also understood from my colleague that the issue was solved.

**Comment by Wroblewski-Piotr** [comment]
Hi,
 
I have problem similar to jotaceperez, described in the comment from 22 May 2017. When I try to compile the oidc-plugin, maven throws me an error regarding the maven repository. I work with Liferay 7.0-ga3 so I using plugin in version 0.2.2

Logs : 

[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for nl.finalist.liferay.oidc:oidc-parent:0.2.2: Could not transfer artifact nl.iprofs.pom:parent:pom:2.0.24 from/to releases-public (https://nexus.iprofs.nl/content/repositories/releases-public): nexus.iprofs.nl and 'parent.relativePath' points at wrong local POM @ line 5, column 13
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project nl.finalist.liferay.oidc:oidc-parent:0.2.2 (C:\Users\Dell\Documents\liferay\liferay-oidc-plugin-oidc-parent-0.2.2\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for nl.finalist.liferay.oidc:oidc-parent:0.2.2: Could not transfer artifact nl.iprofs.pom:parent:pom:2.0.24 from/to releases-public (https://nexus.iprofs.nl/content/repositories/releases-public): nexus.iprofs.nl and 'parent.relativePath' points at wrong local POM @ line 5, column 13: Unknown host nexus.iprofs.nl -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException


I would be very grateful if anyone could help me with this.

**Comment by gvanderploeg** [comment]
Yup, you're right, repos have changed again. I'll open this issue again and try to fix it.. Stay tuned.

**Comment by gvanderploeg** [comment]
@Wroblewski-Piotr Now that I read your comment a bit closer, I realize you're using an older version.
I'm sorry, but I'm not planning to backport the nexus url change into the 0.2.2 release. It's working again in master now, will leave it at that.

**Comment by Wroblewski-Piotr** [comment]
@gvanderploeg Thanks for Your answer. 

Is it posible to get nl.iprofs, in version that I need, to compile plugin in version 0.2.2 from You ? As I wrote in previous comment, I working with Liferay 7.0-ga3 where plugin in version 0.2.2 is used, and I need make only a liitle changes. I do not want to use latest version of plugin because implementation of it could take lot of time, and current solution working really good.


thanks in advance
